### ISSUE TITLE
Formatierungen in Editionsrichtlinien und Nachwort

### ISSUE THREAD

**Issue by ingoboerner** [martinantonmueller/Hermann-Bahr_Arthur-Schnitzler#113]
... das werden einige issues, @martinantonmueller 
[Editionsrichtlinien](http://digitalhumanities.germ.univie.ac.at/exist/apps/hbas/view.html?id=E000001)
[Nachwort](http://digitalhumanities.germ.univie.ac.at/exist/apps/hbas/view.html?id=E000002)

**Comment by martinantonmueller** [comment]
Ich schließ das und machs über Sigle
