### ISSUE TITLE
Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by martinantonmueller** [martinantonmueller/Hermann-Bahr_Arthur-Schnitzler#134]
Komischerweise gehen die Bilder gerade wieder nicht
Bspw.
[https://bahrschnitzler.acdh.oeaw.ac.at/view.html?id=T041001&type=&view-mode=1](https://bahrschnitzler.acdh.oeaw.ac.at/view.html?id=T041001&type=&view-mode=1)
wobei der Bildlink lautet:
http://dse.hephaistos.arz.oeaw.ac.at/exist/apps/hbas/data/images/6322-40.jpg

**Comment by csae8092** [comment]
http://dse.hephaistos.arz.oeaw.ac.at/exist/apps/hbas/data/images/6322-40.jpg

der hier verwendete link ist außerhalb des öaw netzes nicht erreichbar. Eigentlich sollte sich das aber über die Verwendung relativer links lösen lassen? @ingoboerner

**Comment by ingoboerner** [comment]
```
declare variable $config:data-root := $config:app-root || "/data";

declare variable $config:img-root := $config:data-root || "/images";

declare variable $config:img-base-url := substring-before(request:get-url(), request:get-uri()) || "/exist/apps" || substring-after($config:img-root,'db/apps') || "/" ;
```
Die app versucht ja die url zu bestimmen, hab ich nur schlecht gemacht, offensichtlich und das url rewriting nicht bedacht

**Comment by ingoboerner** [comment]
Funktioniert...
