### ISSUE TITLE
Fehler im erschlossenen(?) Datum (1895-02-29) 

### ISSUE THREAD

**Issue by ingoboerner** [martinantonmueller/Hermann-Bahr_Arthur-Schnitzler#138]
in D041408 gibt es ein erschlossenes Datum, das leider für die Sortierfolge genommen wird: <date when="18950229" n="01"/>

Ich möchte eine Suche im Zeitraum StartDatum - EndDatum implementieren; bei derKonvertierung des Strings "1895-02-29" in xs:date generiert mit exist einen Fehler:
```
<message>
err:FORG0001 illegal lexical form for date-time-like value '1895-02-29' Year = 1,895, Month = 2, Day = 29, Hour = -2,147,483,648, Minute = -2,147,483,648, Second = -2,147,483,648, fractionalSecond = null, Timezone = -2,147,483,648 , is not a valid representation of an XML Gregorian Calendar value. [at line 199, column 42] In function: local:getDocsByDateRange(xs:string) [225:72:/db/apps/hbas/modules/api.xqm] api:DocFilterBy(xs:string) [78:49:/db/apps/hbas/modules/api.xqm]
</message>
```
Liegt wahrscheinlich daran, dass 1895 kein Schaltjahr war: https://www.linker.ch/eigenlink/schaltjahre.htm (gibts sicher bessere Quellen); nachdem es sich um ein schlossenes Datum handelt, kann man das in 1895-02-28 ändern? Dann tritt der Fehler nicht mehr auf.

**Comment by martinantonmueller** [comment]
Klar, danke!
