### ISSUE TITLE
Minor fix for scrollbar

### ISSUE THREAD

**Issue by asilcetin** [martinantonmueller/Hermann-Bahr_Arthur-Schnitzler#139]
https://github.com/martinantonmueller/Hermann-Bahr_Arthur-Schnitzler/blob/15a254254dad8f50eb2d6e6d9a2fc175763812aa/app/resources/css/bootstrap-year-calendar.css#L122

Make 215px height

**Comment by martinantonmueller** [comment]
fixed as suggested
